# Generated by Django 4.0.2 on 2022-03-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='account/images/default_avtar.png', upload_to='account/images/'),
        ),
    ]
