# Generated by Django 4.0 on 2021-12-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the publisher.', max_length=50)),
                ('website', models.URLField(help_text='Publishers website')),
                ('email', models.EmailField(help_text="Publisher's email address", max_length=254)),
            ],
        ),
    ]
