# Generated by Django 4.0 on 2021-12-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_book_contributor_review_bookcontributor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='contributors_name',
            new_name='contributors',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher_name',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book_name',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_by',
            new_name='creator',
        ),
    ]
