# Generated by Django 4.0.2 on 2022-02-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='first_names',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='last_names',
            new_name='last_name',
        ),
    ]
