# Generated by Django 4.0.2 on 2022-02-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_rename_first_names_contributor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, through='reviews.BookContributor', to='reviews.Contributor'),
        ),
    ]
