# Generated by Django 4.0.2 on 2022-02-10 19:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_book_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
