# Generated by Django 4.0.2 on 2022-02-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transection_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
